// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'firebase_options.dart';
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB8oPGFMQB6gxJj2RTojRCEPlxd1pSMwU4',
    appId: '1:770779239667:web:fd730117f602d3907f5386',
    messagingSenderId: '770779239667',
    projectId: 'outdoorstore-38497',
    authDomain: 'outdoorstore-38497.firebaseapp.com',
    storageBucket: 'outdoorstore-38497.firebasestorage.app',
    measurementId: 'G-1T0ZFTG1JF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDkWUVEJj_tQFk9EiwUqvWAKDCkeGllm-Y',
    appId: '1:770779239667:android:e37232ad92416e8c7f5386',
    messagingSenderId: '770779239667',
    projectId: 'outdoorstore-38497',
    storageBucket: 'outdoorstore-38497.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD9brkgIA164hNMd-xfFINddvLpz5Z6kLM',
    appId: '1:770779239667:ios:35f25bf5c12573337f5386',
    messagingSenderId: '770779239667',
    projectId: 'outdoorstore-38497',
    storageBucket: 'outdoorstore-38497.firebasestorage.app',
    iosBundleId: 'com.example.outdoorStore',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD9brkgIA164hNMd-xfFINddvLpz5Z6kLM',
    appId: '1:770779239667:ios:35f25bf5c12573337f5386',
    messagingSenderId: '770779239667',
    projectId: 'outdoorstore-38497',
    storageBucket: 'outdoorstore-38497.firebasestorage.app',
    iosBundleId: 'com.example.outdoorStore',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB8oPGFMQB6gxJj2RTojRCEPlxd1pSMwU4',
    appId: '1:770779239667:web:247ee6893967fce27f5386',
    messagingSenderId: '770779239667',
    projectId: 'outdoorstore-38497',
    authDomain: 'outdoorstore-38497.firebaseapp.com',
    storageBucket: 'outdoorstore-38497.firebasestorage.app',
    measurementId: 'G-3M03TE5DSX',
  );
}
